version: '3'
services:
    api:
        build: .
        ports:
            - 8080:8080
        environment:
            DB_USER: 'miraiketai2020'
            DB_PASS: 'miraiketai2020'
            DB_IP: 'db'
            DB_PORT: '3306'
            DB_NAME: 'summer'
        depends_on:
            - 'db'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=root
            - PMA_PASSWORD=miraiketai2020_admin
        ports:
            - 9000:80
        depends_on:
            - 'db'
    db:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'miraiketai2020_admin'
            MYSQL_DATABASE: 'summer'
            MYSQL_USER: 'miraiketai2020'
            MYSQL_PASSWORD: 'miraiketai2020'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./db/sql:/docker-entrypoint-initdb.d